# GitHub Actions for GEOS
#
# Paul Ramsey <pramsey at cleverelephant dot ca>
# Build a geosop container and deploy to GHCR

name: 'Container'

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'web/**'

jobs:

  linux:

    name: 'Linux'
    runs-on: ubuntu-latest

    steps:

    - name: 'Check Out'
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Dockerfile
      run: |
        cp tools/ci/geosop/Dockerfile .

    - name: Build and Push
      if: ${{ github.repository == 'libgeos/geos' }} }}
      uses: docker/build-push-action@v2
      with:
        context: .
        # platforms: linux/amd64,linux/arm64
        platforms: linux/amd64
        push: true
        tags: |
            ghcr.io/libgeos/geosop:latest



