before_script:
    - apt-get update -qq
    - apt-get install -y --allow-unauthenticated build-essential cmake lsb-release
    - lsb_release -a
    - uname -a

test:
  except:
    - master
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make V=0
    - make check V=0
    - install -m 755 /bin/true /usr/local/bin/git2cl
    - make distcheck
